import AdminLayout from "@components/AdminLayout";

export const metadata = {
  title: "Revenue Manager",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <AdminLayout>{children}</AdminLayout>
    </>
  );
}
